### PR TITLE
ig-shuffled-edited.txt

### PR DESCRIPTION
**Pull request by TheRealGeeBee**
There were English sentences in the dataset. Those I removed (to the best of my ability). Also, some Igbo sentences were not complete, I modified those as much as I could, striking out entire sentences I believe made no grammatical sense. I introduced entirely new ones in the process (though some contained no diacritical information due to my keyboard).

I believe this modified dataset is better, in many ways, than the old one. @chrisemezue @edaiofficial

### CODE REVIEW

**Comment by chrisemezue** [comment]
🙏🏽Thank you so much @TheRealGeeBee . Really appreciate your edits. Especially removing the English sentences and nonsensical texts.

**I have a question:**
1. is it advisable to replace words like "China", "Facebook" with "Chaina", "Fesibuk"? What happens to Igbo speakers who are more familiar with the English parts?

**Comment by TheRealGeeBee** [comment]
I am glad you found the edits helpful.

About the issue of replacing the words you specified; they could be
preserved.  But how they are pronounced (in Igbo) would definitely have to
change. The English language, for instance, bears 'anglicised' forms of
words of other languages (like 'blanc mange').

**Comment by chrisemezue** [comment]
Understood.

In terms of it being pronounced in its Igbo form, that can be up to the Igbo speakers who will record the sentences no?

Another issue:
these sentences have already been uploaded to Common Voice (see [here](https://commonvoice.mozilla.org/ig/speak)). I don't really know how to update it with the new sentences you cleaned. 

Regardless, the data you cleaned is still very useful and could be used for other ML use-cases.

**Comment by TheRealGeeBee** [comment]
Thank you for the link you shared. The sentences on Common Voice are great
(I contributed a few of my voice clips in passing). I believe corrections
could still be made where necessary, possibly on the part of voice
contributors.

I read your Igbo Speech-to-Text paper ("OkwuGbe") and I could use some of
the dataset on Common Voice for a similar project.

**Comment by chrisemezue** [comment]
There is also [this ongoing project](https://twitter.com/ChrisEmezue/status/1584614602293542913?s=20&amp;t=rNPLZlZjoDu6trgc9slmYw) which you might be interested in.

@TheRealGeeBee in order for me to merge this PR, could you please rename the igob file you edited. rename it to something like `ig-shuffled-edited.txt`

then commit the new file and i will merge it to the main branch.

**Comment by TheRealGeeBee** [comment]
@chrisemezue I believe I did what you requested for.

**Comment by chrisemezue** [comment]
Yes! Thank you so much!

**Comment by chrisemezue** [comment]
@TheRealGeeBee actually it isn't. Your renaming replaced the original ig-shuffled file that was there. 
What I actually wanted was a new, separate file called `ig-shuffled-clean.txt`

**Comment by chrisemezue** [comment]
I have reverted this merge (see [here](https://github.com/chrisemezue/Igbo-Speech-Dataset/pull/3)).
Please create another pull request with the new file.

**Comment by TheRealGeeBee** [comment]
I created a new pull request with the new file.

**Comment by chrisemezue** [comment]
Thank you

**Pull request merged**
